version: '3'

services:
  sentrycapp:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app
    container_name: sentrycapp
    expose:
      - '8000'
    ports:
      - '8000:8000'
    command: npm run start